############################################
# CloudTechNext AI Document Analyzer inputs
############################################

variable "tenancy_ocid" {
  description = "Tenancy OCID."
  type        = string

  validation {
    condition     = length(var.tenancy_ocid) > 0
    error_message = "tenancy_ocid cannot be empty."
  }
}

variable "compartment_ocid" {
  description = "Target compartment OCID."
  type        = string

  validation {
    condition     = length(var.compartment_ocid) > 0
    error_message = "compartment_ocid cannot be empty."
  }
}

variable "region" {
  description = "OCI region, for example us-chicago-1."
  type        = string

  validation {
    condition     = length(var.region) > 0
    error_message = "region cannot be empty."
  }
}

variable "objectstorage_namespace" {
  description = "Object Storage namespace resolved by CloudTechNext for parity with Resource Manager stack variables."
  type        = string
}

variable "deployment_suffix" {
  description = "Unique suffix generated by CloudTechNext for this deployment."
  type        = string
  default     = "local0000"

  validation {
    condition     = can(regex("^[a-z0-9]{4,16}$", var.deployment_suffix))
    error_message = "deployment_suffix must be 4 to 16 lowercase alphanumeric characters."
  }
}

variable "bucket_name" {
  description = "Unique Object Storage bucket name for AI Document Analyzer documents."
  type        = string
  default     = ""
}

variable "adb_db_name" {
  description = "Unique Autonomous Database db_name for this deployment."
  type        = string
  default     = ""

  validation {
    condition     = var.adb_db_name == "" || can(regex("^[A-Za-z][A-Za-z0-9]{1,13}$", var.adb_db_name))
    error_message = "adb_db_name must start with a letter, contain only letters and numbers, and be at most 14 characters."
  }
}

variable "adb_display_name" {
  description = "Autonomous Database display name for this deployment."
  type        = string
  default     = ""
}

variable "vcn_display_name" {
  description = "VCN display name for this deployment."
  type        = string
  default     = ""
}

variable "instance_display_name" {
  description = "Compute instance display name for this deployment."
  type        = string
  default     = ""
}

variable "source_repo_url" {
  description = "Published AI Document Analyzer Git repository."
  type        = string
  default     = "https://github.com/jgangini/ai-document-analyzer.git"
}

variable "source_ref" {
  description = "Git ref to deploy from the published repository."
  type        = string
  default     = "main"
}

variable "_oci_bucket_name" {
  description = "Object Storage bucket defaults for AI Document Analyzer."

  default = {
    access_type = "NoPublicAccess"
  }
}

variable "_oci_autonomous_database" {
  description = "Autonomous Database profile for AI Document Analyzer launchpad deployments."

  default = {
    compute_count            = 4
    data_storage_size_in_gb  = 20
    data_storage_size_in_tbs = 1
    db_workload              = "OLTP"
    db_version               = "26ai"
    is_free_tier             = false
    is_auto_scaling_enabled  = false
    is_dev_tier              = true
  }
}

variable "autonomous_database_admin_password" {
  description = "ADMIN password for Autonomous Database."
  type        = string
  sensitive   = true

  validation {
    condition = (
      length(var.autonomous_database_admin_password) >= 12 &&
      length(var.autonomous_database_admin_password) <= 30 &&
      can(regex("[A-Z]", var.autonomous_database_admin_password)) &&
      can(regex("[a-z]", var.autonomous_database_admin_password)) &&
      can(regex("[0-9]", var.autonomous_database_admin_password)) &&
      !can(regex("\"", var.autonomous_database_admin_password)) &&
      !can(regex("'", var.autonomous_database_admin_password)) &&
      !can(regex("(?i)admin", var.autonomous_database_admin_password))
    )
    error_message = "Password must be 12-30 characters, include uppercase, lowercase and number, and cannot contain quotes or admin."
  }
}

variable "autonomous_database_wallet_password" {
  description = "Wallet password for Autonomous Database."
  type        = string
  sensitive   = true

  validation {
    condition = (
      length(var.autonomous_database_wallet_password) >= 12 &&
      length(var.autonomous_database_wallet_password) <= 30 &&
      can(regex("[A-Z]", var.autonomous_database_wallet_password)) &&
      can(regex("[a-z]", var.autonomous_database_wallet_password)) &&
      can(regex("[0-9]", var.autonomous_database_wallet_password)) &&
      !can(regex("\"", var.autonomous_database_wallet_password)) &&
      !can(regex("'", var.autonomous_database_wallet_password)) &&
      !can(regex("(?i)admin", var.autonomous_database_wallet_password))
    )
    error_message = "Password must be 12-30 characters, include uppercase, lowercase and number, and cannot contain quotes or admin."
  }
}

variable "autonomous_database_developer_password" {
  description = "AI Document Analyzer application admin password."
  type        = string
  sensitive   = true

  validation {
    condition = (
      length(var.autonomous_database_developer_password) >= 1 &&
      length(var.autonomous_database_developer_password) <= 128 &&
      !can(regex("\"", var.autonomous_database_developer_password)) &&
      !can(regex("[\\r\\n]", var.autonomous_database_developer_password))
    )
    error_message = "Application password must be 1-128 characters and cannot contain double quotes or line breaks."
  }
}

variable "application_username" {
  description = "AI Document Analyzer application login username."
  type        = string
  default     = "admin"

  validation {
    condition = (
      can(regex("^[A-Za-z0-9][A-Za-z0-9_.@-]{0,127}$", var.application_username))
    )
    error_message = "Application username must start with a letter or number and can include letters, numbers, _, ., @ or -."
  }
}

variable "availability_domain_index" {
  description = "Zero-based availability-domain index to use for the compute instance. Useful when a flexible shape has no host capacity in one AD."
  type        = number
  default     = 0

  validation {
    condition     = var.availability_domain_index >= 0 && var.availability_domain_index <= 2
    error_message = "availability_domain_index must be 0, 1, or 2."
  }
}
variable "_oci_vcn" {
  description = "VCN defaults for the AI Document Analyzer Docker host."

  default = {
    cidr_block        = "10.10.0.0/24"
    ingress_tcp_ports = [22, 80]
  }
}

variable "_oci_instance" {
  description = "Compute instance defaults for the CloudTechNext AI Document Analyzer profile."

  default = {
    shape = {
      name          = "VM.Standard.E5.Flex"
      ocpus         = 2
      memory_in_gbs = 16
    }
  }
}
