CREATE TABLE document_sources (
    document_sources_source_id VARCHAR2(512) PRIMARY KEY,
    document_sources_source_uri VARCHAR2(1024) NOT NULL,
    document_sources_source_sha256 VARCHAR2(64) NOT NULL,
    document_sources_title VARCHAR2(512),
    document_sources_mime_type VARCHAR2(128),
    document_sources_metadata_json CLOB CHECK (document_sources_metadata_json IS JSON),
    document_sources_created TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    document_sources_updated TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)
--
CREATE TABLE document_units (
    document_units_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_sources_source_id VARCHAR2(512) NOT NULL,
    document_units_unit_id VARCHAR2(512) NOT NULL,
    document_units_citation_label VARCHAR2(1024) NOT NULL,
    document_units_char_start NUMBER DEFAULT 0 NOT NULL,
    document_units_char_end NUMBER DEFAULT 0 NOT NULL,
    document_units_unit_text CLOB NOT NULL,
    document_units_unit_text_sha256 VARCHAR2(64) NOT NULL,
    document_units_evidence_id VARCHAR2(32) NOT NULL,
    document_units_hash_verified NUMBER(1) DEFAULT 0 NOT NULL,
    document_units_metadata_json CLOB CHECK (document_units_metadata_json IS JSON),
    document_units_created TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    document_units_updated TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_document_units_source
        FOREIGN KEY (document_sources_source_id)
        REFERENCES document_sources(document_sources_source_id),
    CONSTRAINT uk_document_units_source_unit
        UNIQUE (document_sources_source_id, document_units_unit_id),
    CONSTRAINT uk_document_units_evidence_id
        UNIQUE (document_units_evidence_id),
    CONSTRAINT ck_document_units_hash_verified
        CHECK (document_units_hash_verified IN (0, 1))
)
--
CREATE INDEX idx_document_units_source ON document_units(document_sources_source_id)
--
CREATE INDEX idx_document_units_hash ON document_units(document_units_unit_text_sha256)
--
CREATE INDEX idx_document_units_text_ctx
    ON document_units(document_units_unit_text)
    INDEXTYPE IS CTXSYS.CONTEXT
